### ISSUE TITLE
Information of past (not good quality) models

### ISSUE THREAD

**Issue by tarepan** [pstuvwx/Voice_DiscoGAN#4]
Thanks for a great library.  

I read all your codes and found many codes which are not used now.  
I suppose you tried many models & parameters for better results (I respect you.)  
Could you kindly **make the (negative) results open**?  
I am strongly interersted in what model and params are good/bad for spectrogram conversion.  
Even if there are no sample audio, your impression (for example, “time-only Conv cause ぼんやり voice”) is super informative.

**Comment by pstuvwx** [comment]
Thank you for having interest.
The results since last November have been saved with the source code. 
https://drive.google.com/file/d/1jzGKyLuubPk9xIvTXNVlNmtpJ--s0PHj/view?usp=sharing
Before that, I did not copy the source file. (There are audio files, but only the uncertain memo remain for the parameter settings)

**Comment by tarepan** [comment]
Can I access your results & codes?  
It seems that your permission is needed to access above link.

**Comment by tarepan** [comment]
Thank you very much!  
I respect your great efforts!!

**Comment by primejava** [comment]
@pstuvwx It's a great job. Can you give me permission? Thank you.
